import {
  FamilyGroup,
  FamilyMember,
  FireHotspot,
  TrafficIncident,
  SafeZone,
  DisasterAlert,
  AirTraffic,
  MaritimeVessel,
} from '@/types';

export const mockFamilyGroup: FamilyGroup = {
  id: 'fg-001',
  name: 'Dela Cruz Family',
  created_by: 'user-001',
  invite_code: 'BANTAY-DC2024',
  created_at: '2024-01-15T08:00:00Z',
};


export const mockFamilyMembers: FamilyMember[] = [
  {
    id: 'fm-001',
    user_id: 'user-001',
    family_group_id: 'fg-001',
    full_name: 'Juan Dela Cruz',
    role: 'admin',
    status: 'safe',
    last_seen: '2024-01-20T14:30:00Z',
    battery_level: 85,
    distance: 0,
    last_location: { latitude: 14.5995, longitude: 120.9842 },
  },
  {
    id: 'fm-002',
    user_id: 'user-002',
    family_group_id: 'fg-001',
    full_name: 'Maria Dela Cruz',
    role: 'member',
    status: 'safe',
    last_seen: '2024-01-20T14:25:00Z',
    battery_level: 62,
    distance: 1200,
    last_location: { latitude: 14.6042, longitude: 120.9822 },
  },
  {
    id: 'fm-003',
    user_id: 'user-003',
    family_group_id: 'fg-001',
    full_name: 'Pedro Dela Cruz',
    role: 'member',
    status: 'warning',
    last_seen: '2024-01-20T13:45:00Z',
    battery_level: 23,
    distance: 5400,
    last_location: { latitude: 14.5547, longitude: 121.0244 },
  },
  {
    id: 'fm-004',
    user_id: 'user-004',
    family_group_id: 'fg-001',
    full_name: 'Ana Dela Cruz',
    role: 'member',
    status: 'offline',
    last_seen: '2024-01-20T10:00:00Z',
    battery_level: 5,
    distance: 15000,
    last_location: { latitude: 14.6760, longitude: 121.0437 },
  },
];


export const mockFireHotspots: FireHotspot[] = [
  {
    id: 'fh-001',
    location: { latitude: 14.5995, longitude: 120.9842 },
    address: 'Tondo, Manila',
    confidence: 0.92,
    intensity: 'high',
    detected_at: '2024-01-20T14:00:00Z',
    status: 'active',
    affected_radius_meters: 500,
    source: 'FIRMS/VIIRS',
  },
  {
    id: 'fh-002',
    location: { latitude: 14.5547, longitude: 121.0244 },
    address: 'Makati CBD',
    confidence: 0.78,
    intensity: 'medium',
    detected_at: '2024-01-20T13:30:00Z',
    status: 'contained',
    affected_radius_meters: 200,
    source: 'BFP Report',
  },
  {
    id: 'fh-003',
    location: { latitude: 14.6760, longitude: 121.0437 },
    address: 'Quezon City',
    confidence: 0.95,
    intensity: 'critical',
    detected_at: '2024-01-20T14:15:00Z',
    status: 'active',
    affected_radius_meters: 800,
    source: 'FIRMS/MODIS',
  },
  {
    id: 'fh-004',
    location: { latitude: 14.5176, longitude: 121.0509 },
    address: 'Pasig City',
    confidence: 0.65,
    intensity: 'low',
    detected_at: '2024-01-20T12:00:00Z',
    status: 'extinguished',
    affected_radius_meters: 100,
    source: 'Citizen Report',
  },
];


export const mockTrafficIncidents: TrafficIncident[] = [
  {
    id: 'ti-001',
    type: 'accident',
    location: { latitude: 14.5995, longitude: 120.9842 },
    address: 'EDSA cor. Ortigas Ave',
    description: 'Multi-vehicle collision blocking 2 lanes',
    severity: 'high',
    reported_at: '2024-01-20T14:10:00Z',
    status: 'active',
    affected_routes: ['EDSA Northbound', 'Ortigas Ave'],
  },
  {
    id: 'ti-002',
    type: 'congestion',
    location: { latitude: 14.5547, longitude: 121.0244 },
    address: 'C5 Road, Taguig',
    description: 'Heavy traffic due to road construction',
    severity: 'medium',
    reported_at: '2024-01-20T13:45:00Z',
    status: 'active',
    affected_routes: ['C5 Southbound'],
  },
  {
    id: 'ti-003',
    type: 'flood',
    location: { latitude: 14.6760, longitude: 121.0437 },
    address: 'España Blvd, Manila',
    description: 'Knee-deep flooding due to heavy rain',
    severity: 'critical',
    reported_at: '2024-01-20T14:20:00Z',
    status: 'active',
    affected_routes: ['España Blvd', 'Lacson Ave'],
  },
  {
    id: 'ti-004',
    type: 'road_closure',
    location: { latitude: 14.5176, longitude: 121.0509 },
    address: 'Roxas Blvd, Pasay',
    description: 'Road closed for government event',
    severity: 'low',
    reported_at: '2024-01-20T08:00:00Z',
    status: 'active',
    affected_routes: ['Roxas Blvd Northbound'],
  },
];


export const mockSafeZones: SafeZone[] = [
  {
    id: 'sz-001',
    name: 'Rizal Memorial Sports Complex',
    type: 'evacuation_center',
    location: { latitude: 14.5631, longitude: 120.9890 },
    address: 'Vito Cruz, Manila',
    capacity: 5000,
    current_occupancy: 1250,
    contact_number: '(02) 8523-4567',
    is_active: true,
    distance: 2300,
  },
  {
    id: 'sz-002',
    name: 'Philippine General Hospital',
    type: 'hospital',
    location: { latitude: 14.5794, longitude: 120.9870 },
    address: 'Taft Ave, Ermita, Manila',
    capacity: 1500,
    current_occupancy: 1100,
    contact_number: '(02) 8554-8400',
    is_active: true,
    distance: 800,
  },
  {
    id: 'sz-003',
    name: 'Manila Central Fire Station',
    type: 'fire_station',
    location: { latitude: 14.5995, longitude: 120.9842 },
    address: 'Padre Burgos Ave, Ermita',
    capacity: 200,
    current_occupancy: 45,
    contact_number: '(02) 8527-3653',
    is_active: true,
    distance: 1500,
  },
  {
    id: 'sz-004',
    name: 'Quezon City Hall Evacuation Area',
    type: 'evacuation_center',
    location: { latitude: 14.6488, longitude: 121.0509 },
    address: 'Elliptical Road, QC',
    capacity: 3000,
    current_occupancy: 2800,
    contact_number: '(02) 8988-4242',
    is_active: true,
    distance: 8500,
  },
  {
    id: 'sz-005',
    name: 'Barangay 147 Hall',
    type: 'barangay_hall',
    location: { latitude: 14.6042, longitude: 120.9822 },
    address: 'Tondo, Manila',
    capacity: 300,
    current_occupancy: 120,
    contact_number: '(02) 8251-0147',
    is_active: true,
    distance: 500,
  },
];


export const mockDisasterAlerts: DisasterAlert[] = [
  {
    id: 'da-001',
    type: 'typhoon',
    title: 'Typhoon BANTAY Signal #3',
    description: 'Typhoon with maximum sustained winds of 150 kph approaching Metro Manila.',
    severity: 'warning',
    affected_areas: ['Metro Manila', 'Cavite', 'Laguna', 'Rizal', 'Bulacan'],
    instructions: [
      'Stay indoors and away from windows',
      'Prepare emergency supplies',
      'Monitor official PAGASA advisories',
      'Evacuate if in flood-prone areas',
    ],
    issued_at: '2024-01-20T12:00:00Z',
    expires_at: '2024-01-21T12:00:00Z',
    source: 'PAGASA',
    is_active: true,
  },
  {
    id: 'da-002',
    type: 'flood',
    title: 'Flood Warning - Marikina River',
    description: 'Water level at Marikina River has reached critical level (18.5m).',
    severity: 'emergency',
    affected_areas: ['Marikina', 'Pasig', 'Cainta'],
    instructions: [
      'Immediate evacuation for riverside communities',
      'Proceed to nearest evacuation center',
      'Do not attempt to cross flooded areas',
      'Call 911 for rescue assistance',
    ],
    issued_at: '2024-01-20T13:30:00Z',
    source: 'MMDA',
    is_active: true,
  },
  {
    id: 'da-003',
    type: 'earthquake',
    title: 'Earthquake Advisory - Magnitude 4.2',
    description: 'A magnitude 4.2 earthquake was recorded 15km SW of Batangas City.',
    severity: 'advisory',
    affected_areas: ['Batangas', 'Cavite', 'Metro Manila'],
    instructions: [
      'Check for structural damage',
      'Be alert for aftershocks',
      'Stay away from damaged structures',
    ],
    issued_at: '2024-01-20T10:15:00Z',
    source: 'PHIVOLCS',
    is_active: true,
  },
];


export const mockAirTraffic: AirTraffic[] = [
  {
    id: 'at-001',
    flight_number: 'PR 101',
    airline: 'Philippine Airlines',
    origin: 'Manila (MNL)',
    destination: 'Cebu (CEB)',
    status: 'on_time',
    altitude: 32000,
    speed: 520,
    location: { latitude: 13.5, longitude: 122.0 },
    estimated_arrival: '2024-01-20T15:30:00Z',
  },
  {
    id: 'at-002',
    flight_number: '5J 505',
    airline: 'Cebu Pacific',
    origin: 'Manila (MNL)',
    destination: 'Davao (DVO)',
    status: 'delayed',
    altitude: 0,
    speed: 0,
    location: { latitude: 14.5086, longitude: 121.0194 },
    estimated_arrival: '2024-01-20T17:00:00Z',
  },
  {
    id: 'at-003',
    flight_number: 'Z2 772',
    airline: 'AirAsia Philippines',
    origin: 'Clark (CRK)',
    destination: 'Boracay (MPH)',
    status: 'on_time',
    altitude: 28000,
    speed: 480,
    location: { latitude: 13.0, longitude: 121.5 },
    estimated_arrival: '2024-01-20T16:15:00Z',
  },
  {
    id: 'at-004',
    flight_number: 'PR 1845',
    airline: 'Philippine Airlines',
    origin: 'Cebu (CEB)',
    destination: 'Manila (MNL)',
    status: 'diverted',
    altitude: 25000,
    speed: 450,
    location: { latitude: 14.2, longitude: 121.8 },
    estimated_arrival: '2024-01-20T16:45:00Z',
  },
];

export const mockMaritimeVessels: MaritimeVessel[] = [
  {
    id: 'mv-001',
    vessel_name: 'MV Filipinas',
    vessel_type: 'passenger',
    origin_port: 'Manila',
    destination_port: 'Cebu',
    status: 'sailing',
    location: { latitude: 13.5, longitude: 121.5 },
    speed_knots: 18,
    estimated_arrival: '2024-01-21T06:00:00Z',
  },
  {
    id: 'mv-002',
    vessel_name: 'BRP Sierra Madre',
    vessel_type: 'military',
    origin_port: 'Subic',
    destination_port: 'Palawan',
    status: 'sailing',
    location: { latitude: 14.8, longitude: 119.9 },
    speed_knots: 22,
    estimated_arrival: '2024-01-21T12:00:00Z',
  },
  {
    id: 'mv-003',
    vessel_name: 'MV Princess of Stars',
    vessel_type: 'cargo',
    origin_port: 'Manila',
    destination_port: 'Iloilo',
    status: 'distress',
    location: { latitude: 12.8, longitude: 121.2 },
    speed_knots: 0,
    estimated_arrival: '2024-01-21T18:00:00Z',
  },
  {
    id: 'mv-004',
    vessel_name: 'FB Karagatan',
    vessel_type: 'fishing',
    origin_port: 'Navotas',
    destination_port: 'Navotas',
    status: 'anchored',
    location: { latitude: 14.65, longitude: 120.93 },
    speed_knots: 0,
    estimated_arrival: '2024-01-20T18:00:00Z',
  },
];
